[tox]
minversion = 3.0.0
envlist = py310, py311, py312, py313, py314, lint, doccheck, coverage, mypy, black
isolated_build = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
description = Run unit tests
deps =
    pytest
passenv = SUNDIALS_INST HOME
install_command = pip install --no-cache-dir --no-binary scikits-odes-sundials {opts} {packages}
setenv =
    PYTHONPATH = {toxinidir}
    HOME = {env:HOME}
allowlist_externals =
    bash
commands =
    pytest tests/


[testenv:lint]
description = Run Ruff linter on code and docstrings
deps = ruff
commands =
    ruff check src/

[testenv:doccheck]
description = Check Python docstring coverage with interrogate
deps = interrogate
commands =
    interrogate src/ --fail-under=90 --verbose

[testenv:coverage]
deps =
    pytest
    pytest-cov
usedevelop = True
setenv =
    PYTHONPATH = {toxinidir}/src
    COVERAGE_PROCESS_START = {toxinidir}/.coveragerc

allowlist_externals =
    bash
commands =
    coverage run --source=reactormodels -m pytest tests/
    coverage report --fail-under=80
    coverage html

[testenv:mypy]
description = Run mypy type checks
deps =
    mypy
    scipy-stubs
commands =
    mypy src/

[testenv:black]
description = Check code formatting with black
deps = black
commands =
    black --check --target-version py310 src/