name: Lint

on:
  pull_request:
    branches:
      - "**"

  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SUNDIALS and Fortran Compiler (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc sundials
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

          GFORTRAN_BIN="$(find "$(brew --prefix gcc)/bin" -name 'gfortran-*' | head -n 1)"
          ln -sf "$GFORTRAN_BIN" /opt/homebrew/bin/gfortran

          which gfortran
          gfortran --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run linter
        run: tox -e lint
